language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
before-script:
  - npm install
script:
  - npm test
# slack notifications configuration
notifications:
  slack: andela:klJW0ykyWuYE3i66GObhcUT5
