/* eslint-disable import/prefer-default-export */
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const LOGIN_BY_EMAIL_SUCCESS = "LOGIN_BY_EMAIL_SUCCESS";
export const LOGIN_BY_EMAIL_FAILURE = "LOGIN_BY_EMAIL_FAILURE";
export const LOGIN_BY_SOCIAL = "LOGIN_BY_SOCIAL";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const SKIP_WALKTHROUGH = "SKIP_WALKTHROUGH";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";

export const WELCOME_MESSAGE = "WELCOME_MESSAGE_SUCCESS";

// create and get article actions
export const CREATE_ARTICLE_SUCCESS = "CREATE_ARTICLE_SUCCESS";
export const CREATE_ARTICLE_FAILURE = "CREATE_ARTICLE_FAILURE";
export const GET_SPECIFIC_ARTICLE_SUCCESS = "GET_SPECIFIC_ARTICLE_SUCCESS";
export const GET_TAG_RELATED_ARTICLES_SUCCESS = "GET_TAG_RELATED_ARTICLES_SUCCESS";
