/* eslint-disable import/prefer-default-export */
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const LOGIN_BY_EMAIL_SUCCESS = "LOGIN_BY_EMAIL_SUCCESS";
export const LOGIN_BY_EMAIL_FAILURE = "LOGIN_BY_EMAIL_FAILURE";
export const LOGIN_BY_SOCIAL = "LOGIN_BY_SOCIAL";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const SKIP_WALKTHROUGH = "SKIP_WALKTHROUGH";
