/* eslint-disable import/prefer-default-export */
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOGIN_BY_EMAIL_SUCCESS = "LOGIN_BY_EMAIL_SUCCESS";
export const LOGIN_BY_EMAIL_FAILURE = "LOGIN_BY_EMAIL_FAILURE";
export const LOGIN_BY_SOCIAL = "LOGIN_BY_SOCIAL";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOG_OUT = "LOG_OUT";

export const SKIP_WALKTHROUGH = "SKIP_WALKTHROUGH";

export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";

export const CREATE_ARTICLE_SUCCESS = "CREATE_ARTICLE_SUCCESS";
export const CREATE_ARTICLE_FAILURE = "CREATE_ARTICLE_FAILURE";
export const GET_SPECIFIC_ARTICLE_SUCCESS = "GET_SPECIFIC_ARTICLE_SUCCESS";
export const GET_TAG_RELATED_ARTICLES_SUCCESS = "GET_TAG_RELATED_ARTICLES_SUCCESS";
export const RETRIEVE_ALL_ARTICLES_SUCCESS = "RETRIEVE_ALL_ARTICLES_SUCCESS";
export const RETRIEVE_ALL_ARTICLES_FAILURE = "RETRIEVE_ALL_ARTICLES_FAILURE";
export const RETRIEVE_ALL_ARTICLES_IS_LOADING = "RETRIEVE_ALL_ARTICLES_IS_LOADING";
export const DELETE_ARTICLE_SUCCESS = "DELETE_ARTICLE_SUCCESS";
export const EDIT_ARTICLE_SUCCESS = "EDIT_ARTICLE_SUCCESS";

export const LIKE_ARTICLE_REQUEST = "LIKE_ARTICLE_REQUEST";
export const LIKE_ARTICLE_SUCCESS = "LIKE_ARTICLE_SUCCESS";
export const LIKE_ARTICLE_FAILURE = "LIKE_ARTICLE_FAILURE";

export const DISLIKE_ARTICLE_REQUEST = "DISLIKE_ARTICLE_REQUEST";
export const DISLIKE_ARTICLE_SUCCESS = "DISLIKE_ARTICLE_SUCCESS";
export const DISLIKE_ARTICLE_FAILURE = "LIKE_ARTICLE_FAILURE";

export const RATE_ARTICLE_SUCCESS = "RATE_ARTICLE_SUCCESS";
export const GET_ARTICLE_RATING_SUCCESS = "GET_ARTICLE_RATING_SUCCESS";

export const BOOKMARK_ARTICLE_SUCCESS = "BOOKMARK_ARTICLE_SUCCESS";
export const BOOKMARK_ARTICLE_FAILURE = "BOOKMARK_ARTICLE_FAILURE";
export const UN_BOOKMARK_ARTICLE_SUCCESS = "UN_BOOKMARK_ARTICLE_SUCCESS";
export const UN_BOOKMARK_ARTICLE_FAILURE = "UN_BOOKMARK_ARTICLE_FAILURE";
export const GET_ALL_BOOKMARKS_SUCCESS = "GET_ALL_BOOKMARKS_SUCCESS";

export const STATS_REQUEST = "STATS_REQUEST";
export const STATS_REQUEST_FAILURE = "STATS_REQUEST_FAILURE";
export const STATS_REQUEST_SUCCESS = "STATS_REQUEST_SUCCESS";

export const READ_STATS_REQUEST = "READ_STATS_REQUEST";
export const READ_STATS_REQUEST_FAILURE = "READ_STATS_REQUEST_FAILURE";
export const READ_STATS_REQUEST_SUCCESS = "READ_STATS_REQUEST_SUCCESS";

export const GET_ARTICLE_COMMENTS_SUCCESS = "GET_ARTICLE_COMMENTS_SUCCESS";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const GET_REPLY_COMMENT_SUCCESS = "GET_REPLY_COMMENT_SUCCESS";
export const GET_ARTICLE_COMMENTS_FAILURE = "GET_ARTICLE_COMMENTS_FAILURE";
export const GET_REPLY_COMMENT_FAILURE = "GET_REPLY_COMMENT_FAILURE";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";

// list all users
export const REQUEST_PROFILES = "REQUEST_PROFILES";
export const REQUEST_PROFILES_SUCCESS = "REQUEST_PROFILES_SUCCESS";
export const REQUEST_PROFILES_FAILURE = "REQUEST_PROFILES_FAILURE";

// specific user profile
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_FAILURE = "GET_USER_PROFILE_FAILURE";
